# Site settings
title: iOS Dev Practice
email: wiley@iosdevpractice.com
description: "Practice iOS app development without the hand-holding. Given a brief design specification, build an app. No more blindly following tutorials. Think a little and learn a lot."
baseurl: ""
url: "http://www.iosdevpractice.com"
twitter_username: wileywimberly
github_username: iosdevpractice

# Build settings
markdown: kramdown
permalink: pretty
